import numpy as np
import os
import struct

def generate_header_file(template_file, output_file):
    """Generate a C header file with the constants embedded"""
    script_directory = os.path.dirname(os.path.abspath(__file__))
    npz_file_path = os.path.join(script_directory, "dftd3_params.npz")
    
    print(f"Loading parameters from: {npz_file_path}")
    # Ensure the output directory exists
    os.makedirs(os.path.dirname(output_file), exist_ok=True)
    
    # Load parameters
    d3_params = np.load(npz_file_path)
    # Convert to numpy arrays with C-order if needed
    c6ab = d3_params['c6ab'].astype(np.float32).copy(order='C')
    r0ab = d3_params['r0ab'].astype(np.float32).copy(order='C')
    rcov = d3_params['rcov'].astype(np.float32).copy(order='C')
    r2r4 = d3_params['r2r4'].astype(np.float32).copy(order='C')
    
    # Create the header file
    with open(output_file, 'w') as f:
        f.write('// Auto-generated constants.h file - DO NOT EDIT MANUALLY\n')
        f.write('// Generated by generate_constants.py\n\n')
        
        # Include standard headers
        f.write('#include <assert.h>\n')
        f.write('#include <stddef.h>\n')
        f.write('#include <stdlib.h>\n')
        f.write('#include <stdio.h>\n')
        f.write('#include <stdint.h>\n')
        f.write('#include "d3.h"\n\n')
        
        # Write d3 system parameters
        f.write('// d3 system parameters\n')
        f.write('#define NUM_ELEMENTS 95\n')
        f.write('#define NUM_REF_C6 5\n')
        f.write('#define NUM_C6AB_ENTRIES 3\n\n')
        
        # Type definition
        f.write('// type definitions\n')
        f.write('typedef float real_t; // type for real numbers\n\n')
        
        # Write constant declarations with initialization
        f.write('// constant values for d3 system - auto-generated\n')
        
        # Define constants as static const to keep them in read-only memory
        f.write('static const float c6ab_ref[NUM_ELEMENTS][NUM_ELEMENTS][NUM_REF_C6][NUM_REF_C6][NUM_C6AB_ENTRIES] = {\n')
        for i in range(c6ab.shape[0]):
            f.write('    {\n')
            for j in range(c6ab.shape[1]):
                f.write('        {\n')
                for k in range(c6ab.shape[2]):
                    f.write('            {\n')
                    for l in range(c6ab.shape[3]):
                        f.write('                {')
                        for m in range(c6ab.shape[4]):
                            f.write(f'{c6ab[i,j,k,l,m]:.10f}')
                            if m < c6ab.shape[4] - 1:
                                f.write(', ')
                        f.write('}')
                        if l < c6ab.shape[3] - 1:
                            f.write(',')
                        f.write('\n')
                    f.write('            }')
                    if k < c6ab.shape[2] - 1:
                        f.write(',')
                    f.write('\n')
                f.write('        }')
                if j < c6ab.shape[1] - 1:
                    f.write(',')
                f.write('\n')
            f.write('    }')
            if i < c6ab.shape[0] - 1:
                f.write(',')
            f.write('\n')
        f.write('};\n\n')
        
        # r0ab array
        f.write('static const float r0ab[NUM_ELEMENTS][NUM_ELEMENTS] = {\n')
        for i in range(r0ab.shape[0]):
            f.write('    {')
            for j in range(r0ab.shape[1]):
                f.write(f'{r0ab[i,j]:.10f}')
                if j < r0ab.shape[1] - 1:
                    f.write(', ')
            f.write('}')
            if i < r0ab.shape[0] - 1:
                f.write(',')
            f.write('\n')
        f.write('};\n\n')
        
        # rcov array
        f.write('static const float rcov[NUM_ELEMENTS] = {')
        for i in range(rcov.shape[0]):
            if i % 8 == 0:
                f.write('\n    ')
            f.write(f'{rcov[i]:.10f}')
            if i < rcov.shape[0] - 1:
                f.write(', ')
        f.write('\n};\n\n')
        
        # r2r4 array
        f.write('static const float r2r4[NUM_ELEMENTS] = {')
        for i in range(r2r4.shape[0]):
            if i % 8 == 0:
                f.write('\n    ')
            f.write(f'{r2r4[i]:.10f}')
            if i < r2r4.shape[0] - 1:
                f.write(', ')
        f.write('\n};\n\n')
        
        # Add dummy initialization function that doesn't do anything since constants are now built-in
        f.write('/**\n')
        f.write(' * @brief Dummy function for init_params compatibility\n')
        f.write(' * @note This function is now a no-op since parameters are compiled into the binary\n')
        f.write(' */\n')
        f.write('void init_params() {\n')
        f.write('    // Constants are now statically defined, no initialization needed\n')
        f.write('}\n')

if __name__ == "__main__":
    script_directory = os.path.dirname(os.path.abspath(__file__))
    output_file = os.path.join(os.path.dirname(script_directory), "src", "gen_constants.h")
    generate_header_file(None, output_file)
    print(f"Generated header file: {output_file}")
